### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sorcerer-com** [sorcerer-com/MyHome#1]
- [ ] ~~Add sound sensor / add to security alarm~~
- [ ] ~~DNS name and HTTPS (https://letsencrypt.org/)~~
- [x] Add visibility to BaseSystem
- [x] Support multiple cameras in SecuritySystem
- [x] Remove Emon and RFNetwork code from multi-sensors code
- [x] Add alarm if curtain sensor isn't reachable for some time
- [x] Add auto-update functionality (check the repo, add message in UI, click, pull and restart)
- [x] Define two types of generic sensors - USB and WiFi
- [x] Define way to be able to initiate data transfer from the system or from the sensor
- [ ] WiFi Mesh for generic module
- [x] Define ~~actuators~~ drivers (GPIO, lamp switch/dimmer, WiFi magic light bulb, etc.)
- [ ] Define way actuators to take action from the system (one way communication)
- [ ] Security System - simulate lamp switching
- [ ] Define some graphical programming (ex: Scratch, Blocky, etc.) - for lamp turning on (when it's after 22 o'clock and lighting below...), may be for sensors alerting (threshold) too

AI System:
- [ ] ~~Face detection~~
- [x] kolko e X po Y (with variables)
- [ ] write notes and reminders
- [x] kakva e temperaturata v staiata
- [ ] AI Names: Sample, Bit, Byte, Dummy, Proto(prototype), MyIA(my intelligence artificial) - Мая

Others:
- [ ] MultiSensor as smart clock (with display)
- [ ] UPS system
- [ ] Smart door lock (Xiaomi Sherlock)
- [ ] WiFi water meter
- [x] WiFi IP camera
- [x] OwnCloud / ~~NextCloud~~
- [x] ~~gitlab~~ / gogs
- [ ] ~~fwbackups on external hdd~~

Update raspberry
Update External libraries
www.robotics-bg.com
www.chepakov.com
www.roboleague.com
